# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Aniraj Kesavan
tagline:          ''
description:      ''
url:              http://anirajk.github.io

author:
  name:           'Aniraj Kesavan'
  url:            https://twitter.com/anirajkesavan

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/anirajk
twitter_username:     anirajkesavan
github_username:      anirajk
linkedin_username:    anirajkesavan
google_plus_username: +AnirajKesavan
facebook_username:    aniraj.kesavan
